kind = "DojoModel"
class_hash = "0x7e78f305f592ec36ef200510998304126bc136a78fa91892bd45efda4a134d3"
original_class_hash = "0x7e78f305f592ec36ef200510998304126bc136a78fa91892bd45efda4a134d3"
abi = "manifests/dev/abis/base/models/tic_tac_toe_models_board_board.json"
name = "tic_tac_toe::models::board::board"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "slots"
type = "u32"
key = false

[[members]]
name = "occupied"
type = "u32"
key = false
