kind = "DojoContract"
class_hash = "0x16c94e82a81e5bfca007f15d61185e45ad96cc118393d55493447a4d5eeaed8"
original_class_hash = "0x16c94e82a81e5bfca007f15d61185e45ad96cc118393d55493447a4d5eeaed8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/tic_tac_toe_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "tic_tac_toe::systems::actions::actions"
